# Generated by Django 5.2.3 on 2025-06-30 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='physiotherapist',
            field=models.ForeignKey(limit_choices_to={'user_type': 'physiotherapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapist_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentdocument',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentfeedback',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='appointments.appointment'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'start_time'], name='appointment_date_e19e79_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'date'], name='appointment_patient_ec58f0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['physiotherapist', 'date'], name='appointment_physiot_6018d8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_type'], name='appointment_appoint_6f2f79_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
        migrations.AddIndex(
            model_name='appointmentdocument',
            index=models.Index(fields=['appointment', 'document_type'], name='appointment_appoint_e76ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentdocument',
            index=models.Index(fields=['created_at'], name='appointment_created_d1d6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentfeedback',
            index=models.Index(fields=['rating'], name='appointment_rating_58fa96_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentfeedback',
            index=models.Index(fields=['created_at'], name='appointment_created_20df35_idx'),
        ),
    ]
